[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"
  NEXT_USE_SSR = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"